language: r

cache: packages

sudo: required

env:
 global:
   - _R_CHECK_FORCE_SUGGESTS_: FALSE

r:
  - 3.2
  - 3.3
  - 3.4
  - 3.5
  - devel
  
os:
  - linux
  - osx
  
matrix:
  exclude:
  allow_failures:
  - r: devel
    os: linux
  - r: devel
    os: osx
  - r: 3.5
    os: osx
  - r: 3.5
    os: linux
  - r: 3.4
    os: osx
  - r: 3.3
    os: osx
  - r: 3.2
    os: osx

r_github_packages:
  - r-lib/covr
  - nlmixrdevelopment/dparser-R
  - nlmixrdevelopment/PreciseSums
  - nlmixrdevelopment/SnakeCharmR

after_success:
  - Rscript -e 'covr::codecov(line_exclusions=c("R/RxODE-win-setup.R", "src/errmsg.f", "src/rprint.c", "R/dsl.R", "R/rxValidate.R","R/rxSolve-gen.R","R/rxsympy.R","R/version.R", "R/rxSolve.c", "R/rxShiny.R"), function_exclusions=c("print\\.","summary\\.","\\.onLoad"))'