language: r
r:
  - 3.2
  - 3.3
  - devel
  
os:
  - linux
  - osx

matrix:
  exclude:
  allow_failures:
  - r: devel
    os: linux
  - r: devel
    os: osx


r_github_packages:
  - jimhester/covr
  - mattfidler/dparser-R

after_success:
  - Rscript -e 'covr::codecov()'