language: r
cache: packages
script: -|
  R CMD build .
  travis_wait 20 R CMD check RxODE*tar.gz
  
r:
  - 3.2
  - 3.3
  - devel
  
os:
  - linux
  - osx

matrix:
  exclude:
  allow_failures:
  - r: devel
    os: linux
  - r: devel
    os: osx


r_github_packages:
  - jimhester/covr
  - nlmixrdevelopment/dparser-R

after_success:
  - travis_wait 20 Rscript -e 'covr::codecov()'