language: r

cache: packages

r:
  - 3.2
  - 3.3
  - 3.4
  - devel
  
os:
  - linux
  - osx
  
matrix:
  exclude:
  allow_failures:
  - r: devel
    os: linux
  - r: devel
    os: osx
  - r: 3.3
    os: osx
  - r: 3.2
    os: osx

r_github_packages:
  - jimhester/covr
  - nlmixrdevelopment/dparser-R
  - nlmixrdevelopment/PreciseSums

after_success:
  - travis_wait 20 Rscript -e 'covr::codecov(line_exclusions=c("R/RxODE-win-setup.R", "src/errmsg.f", "src/rprint.c"))'