language: r

cache: packages

sudo: required

env:
 global:
   - _R_CHECK_FORCE_SUGGESTS_: FALSE

r:
  - 3.4
  - 3.5
  - devel
  
os:
  - linux
  - osx
  
matrix:
  exclude:
  allow_failures:
  - r: devel
    os: linux
  - r: devel
    os: osx
  - r: 3.5
    os: osx
  - r: 3.4
    os: osx
  - r: 3.3
    os: osx

addons:
  apt:
    packages:
      - libudunits2-dev

r_github_packages:
  - r-lib/covr
  - nlmixrdevelopment/n1qn1
  - nlmixrdevelopment/dparser-R
  - nlmixrdevelopment/PreciseSums
  - nlmixrdevelopment/SnakeCharmR

after_success:
  - Rscript -e 'covr::codecov(function_exclusions="(print\\.|summary\\.|\\.onLoad)")'