language: r
r:
  - 3.2
  - 3.3
  - devel
  
os:
  - linux
  - osx

matrix:
  exclude:
  - r: 3.3
    os: osx
  - r: devel
    os: osx
  allow_failures:
  - r: devel
    os: linux

r_github_packages:
  - jimhester/covr

after_success:
  - Rscript -e 'covr::codecov(line_exclusions=c("R/genShinyApp.template.R","src/errmsg.f","src/rprintf.c","src/vode.f" "src/dlsoda.f" "src/dop853.c" "src/gram.c" "src/lex.c" "src/lr.c" "src/mkdparse.c" "src/opkda1_abbr.f" "src/opkda2.f" "src/scan.c" "src/symtab.c" "src/util.c" "src/version.c" "src/write_tables.c"))'