language: r

cache: packages

sudo: required

env:
 global:
   - _R_CHECK_FORCE_SUGGESTS_: FALSE
   - CODECOV_TOKEN: c1a47ffb-e5b5-420a-a0ed-6df480bcb833

r:
  - 3.6
  - devel
  
os:
  - linux
  - osx
  
matrix:
  exclude:
  allow_failures:
  - r: devel
    os: linux
  - r: devel
    os: osx
  - r: 3.6
    os: osx

apt_packages:
  - libudunits2-dev

before_install:
  - if [ $TRAVIS_OS_NAME = osx ]; then brew install cmake gmp mpfr libmpc || true; fi
  
warnings_are_errors: true

r_github_packages:
  - nlmixrdevelopment/n1qn1
  - nlmixrdevelopment/dparser-R
  - nlmixrdevelopment/PreciseSums
  - nlmixrdevelopment/SnakeCharmR
  - symengine/symengine.R
after_success:
  - Rscript -e 'covr::codecov(token="c1a47ffb-e5b5-420a-a0ed-6df480bcb833")'
