on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

rchk:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: r-lib/actions/run-rchk@master
      with:
        apt: libcurl4-openssl-dev libcairo2-dev libpango1.0-dev libxt-dev libssl-dev libxml2-dev libtiff5-dev libudunits2-dev xclip zlib1g-dev cmake libgmp-dev libmpfr-dev libmpc-dev devscripts libgit2-dev
